In [3]:
# NumPy Kütüphanesi
"""
- Matrisler için hesaplama kolaylığı sağlar.
- NumPy aslında bir array yapısıdır
"""
import numpy as np
# 1*15 boyutunda bir array-dizi
dizi = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(dizi)
print(dizi.shape) # arrayin boyutu

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(15,)


In [9]:
dizi2 = dizi.reshape(3,5)
print("Şekil: ",dizi2.shape)
print("Boyut: ",dizi2.ndim)
print("Veri Tipi: ",dizi2.dtype.name)
print("Boy: ",dizi2.size)
print("Type: ",type(dizi2)) # array type

Şekil:  (3, 5)
Boyut:  2
Veri Tipi:  int32
Boy:  15
Type:  <class 'numpy.ndarray'>


In [21]:
# İki Boyutlu Array Oluşturma
dizi2D = np.array([[1,2,3,4], [5,6,7,8], [9,8,7,5]])
print(dizi2D)
# Sıfırlardan Oluşan Bir Array
sifir_dizi = np.zeros((3,4))
print(sifir_dizi)
# Her bir sıfır değeri bir piksele denk gelen genlik değeridir.
# Birlerden Oluşan Bir Array
bir_dizi = np.ones((3,4))
print(bir_dizi)
# Boş Array
bos_dizi = np.empty((3,4))
print(bos_dizi) # Boş(0'a ne kadar yakınsa) olacak

[[1 2 3 4]
 [5 6 7 8]
 [9 8 7 5]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [24]:
# arange(x,y,basamak)
dizi_aralik = np.arange(10,50,5)
print(dizi_aralik)
# linspace(x,y,basamak) => x ve y dahil olarak basamak kadar bölüyor
dizi_bosluk = np.linspace(10,20,5)
print(dizi_bosluk)

[10 15 20 25 30 35 40 45]
[10.  12.5 15.  17.5 20. ]


In [25]:
# Float Array
float_array = np.float32([[1,2],[3,4]])
print(float_array)

[[1. 2.]
 [3. 4.]]


In [32]:
# Matematiksel İşlemler
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a-b)
print(a**2)
# Dizi Elemanı Toplama
print(np.sum(a))
# Max Değer
print(np.max(a))
# Min Değer
print(np.min(a))
# Ortalama
print(np.mean(a))
# Medyan Değeri
print(np.median(a))

[5 7 9]
[-3 -3 -3]
[1 4 9]
6
3
1
2.0
2.0


In [34]:
# Rastgele Sayı Üretme [0,1] arasında sürekli uniform 3*3
rastgele_dizi = np.random.random((3,3))
print(rastgele_dizi) # BAK

[[0.4572457  0.87282352 0.55444206]
 [0.97686807 0.87303848 0.62904128]
 [0.35115625 0.42240757 0.34294394]]


In [40]:
# index 
dizi = np.array([1,2,3,4,5,6,7])
print(dizi[0])
# Dizinin ilk elemanı 4 elemanı
print(dizi[0:4])
# Dizinin Tersi
print(dizi[::-1])

1
[1 2 3 4]
[7 6 5 4 3 2 1]


In [49]:
dizi2D = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(dizi2D)
# Dizinin 1.satır ve 1.sütununda bulunan elemanı (index)
print(dizi2D[1,1])
# 1.Sütun ve Tüm Satırlar(:)
print(dizi2D[:,1])
# Satır 1, Sütun 1,2,3
print(dizi2D[1,1:4])
# Dizinin son satır tüm sütunları
print(dizi2D[1,:])
# print(dizi2D[-1,:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
7
[2 7]
[7 8 9]
[ 6  7  8  9 10]


In [54]:
dizi2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(dizi2D)
# Vektör haline getirme
vektor = dizi2D.ravel()
print(vektor)
# Resimleri düzleştirmek için ihtiyaç var.
maksimum_sayinin_indeksi = vektor.argmax() 
print(maksimum_sayinin_indeksi)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
8
